load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "ArgParser_UT",
    srcs = [
        "ArgParser_UT.cpp",
    ],
    deps = [
        "//src/tsync-daemon:arg_parser",
        "@googletest//:gtest_main",
    ]
)
