load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "TimeBaseAccessorFactory_UT",
    srcs = [
        "TimeBaseAccessorFactory_UT.cpp",
    ],
    deps = [
        "//src/tsync-utility-lib:tsync_utility",
        "@googletest//:gtest_main",
    ]
)
