#ifndef FLATBUFFERS_GENERATED_TSYNCFLATCFG_TSYNCFLATBUFFER_ADDON_H_
#define FLATBUFFERS_GENERATED_TSYNCFLATCFG_TSYNCFLATBUFFER_ADDON_H_

#include "flatbuffers/score.h"

// generated by option: --score-extension
namespace flatbuffers {
namespace score {

class TSYNC : public FcBase<TSYNC> {
private:
    /* coverity[autosar_cpp14_a0_1_3_violation] The private method _versionMajor() is used by CRTP class FcBase<TSYNC>
     * and intentionally not accessible through the user API. */
    static constexpr int32_t _versionMajor() noexcept {
        return static_cast<int32_t>(3L);
    }
    /* coverity[autosar_cpp14_a0_1_3_violation] The private method _versionMinor() is used by CRTP class FcBase<TSYNC>
     * and intentionally not accessible through the user API. */
    static constexpr int32_t _versionMinor() noexcept {
        return static_cast<int32_t>(1L);
    }
    /* coverity[autosar_cpp14_a0_1_3_violation] The private method _name() is used by CRTP class FcBase<TSYNC> and
     * intentionally not accessible through the user API. */
    static constexpr const char* _name() noexcept {
        return "TSYNC";
    }
    /* RULECHECKER_comment(1, 1, check_friend_declaration, "The CRTP class FcBase<TSYNC> requires a friend declaration
     * to access private methods. However, these methods should not be accessible through the user API.", true) */
    friend FcBase<TSYNC>;
};

}  // namespace score
}  // namespace flatbuffers

#endif
